/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  Get,
  Param,
  Patch,
  Post,
  Query,
  Req,
  UploadedFile,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { FileInterceptor } from '@nestjs/platform-express';
import {
  ApiBody,
  ApiConsumes,
  ApiOperation,
  ApiParam,
  ApiQuery,
  ApiSecurity,
  ApiTags,
} from '@nestjs/swagger';
import multer from 'multer';
import { Roles } from 'src/common/decorator/rolesDecorator';
import { AuthGuard } from 'src/common/guards/auth/auth.guard';
import { CreateUserDto } from './dto/create-user.dto';
import { ROLE } from './entities/role.entity';
import { UserService } from './user.service';
import { UserRole } from '@prisma/client';
// import { uploadFileToS3 } from 'src/utils/common/S3FileUpload';
import { uploadFileToCloudinary } from 'src/utils/common/uploadFileToCloudinary';

@ApiTags('User')
@Controller('user')
export class UserController {
  constructor(
    private readonly userService: UserService,
    private configService: ConfigService,
  ) {}

  private roleNeedsDepartment(role: UserRole): boolean {
    return (
      role === UserRole.STUDENT ||
      role === UserRole.FACULTY ||
      role === UserRole.DEPARTMENT_HEAD
    );
  }

  private async registerWithFixedRole(
    role: UserRole,
    body: { data: string },
    image?: Express.Multer.File,
  ) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(body.data);
    } catch {
      throw new BadRequestException('Invalid JSON format in data field');
    }

    let userRegistrationData: Partial<CreateUserDto> & { image?: string } = {};
    if (parsed && typeof parsed === 'object') {
      userRegistrationData = parsed as Partial<CreateUserDto> & {
        image?: string;
      };
    }

    userRegistrationData.role = role;

    if (this.roleNeedsDepartment(role) && !userRegistrationData.departmentId) {
      throw new BadRequestException(
        `departmentId is required for ${role} role`,
      );
    }

    if (image) {
      const imageLink = await uploadFileToCloudinary(image, this.configService, {
        folder: 'user-profile-images',
      });
      userRegistrationData.image = imageLink as string;
    }

    return this.userService.create(userRegistrationData as CreateUserDto);
  }

  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Get all users (with pagination/filter)' })
  @ApiQuery({ name: 'page', required: false, type: Number, example: 1 })
  @ApiQuery({ name: 'limit', required: false, type: Number, example: 10 })
  @ApiQuery({ name: 'isBlocked', required: false, type: Boolean, example: false })
  @Roles(ROLE.SUPER_ADMIN, ROLE.REGISTRAR)
  @Get()
  findAll(
    @Query('page') page?: number,
    @Query('limit') limit?: number,
    @Query('isBlocked') isBlocked?: boolean,
  ) {
    return this.userService.findAll(page, limit, isBlocked);
  }
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Get my profile' })
  @Roles()
  @Get('/me')
  me(@Req() req: Request & { user: { id: string } }) {
    return this.userService.getMyProfileInfo(req.user.id);
  }

  @ApiOperation({ summary: 'Temp login by email' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
      },
      required: ['email'],
    },
  })
  @Post('/temp-login')
  async TempLogin(@Body('email') email: string) {
    return this.userService.tempLogin(email);
  }
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Get my dashboard statics' })
  @Roles()
  @Get('/dashboard-statics')
  dashboardStatics(@Req() req: Request & { user: { id: string } }) {
    return this.userService.getStatics(req.user.id);
  }

  @ApiOperation({ summary: 'Register user (multipart form-data)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          description:
            'Stringified JSON body. For STUDENT role, studentId is auto-generated by server based on departmentId.',
          example:
            '{\n  "STUDENT": {\n    "firstName": "Student",\n    "lastName": "One",\n    "email": "student1@example.com",\n    "role": "STUDENT",\n    "departmentId": "3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n    "phoneNumber": "+8801712345678",\n    "password": "123456"\n  },\n  "FACULTY": {\n    "firstName": "Faculty",\n    "lastName": "One",\n    "email": "faculty1@example.com",\n    "role": "FACULTY",\n    "employeeId": "FAC-1001",\n    "designation": "Assistant Professor",\n    "departmentId": "3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n    "phoneNumber": "+8801712345678",\n    "password": "123456"\n  },\n  "DEPARTMENT_HEAD": {\n    "firstName": "Head",\n    "lastName": "OfDept",\n    "email": "head1@example.com",\n    "role": "DEPARTMENT_HEAD",\n    "employeeId": "DH-1001",\n    "designation": "Professor",\n    "departmentId": "3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n    "phoneNumber": "+8801712345678",\n    "password": "123456"\n  },\n  "REGISTRAR": {\n    "firstName": "Registrar",\n    "lastName": "One",\n    "email": "registrar1@example.com",\n    "role": "REGISTRAR",\n    "employeeId": "REG-1001",\n    "designation": "Registrar",\n    "phoneNumber": "+8801712345678",\n    "password": "123456"\n  },\n  "SUPER_ADMIN": {\n    "firstName": "Super",\n    "lastName": "Admin",\n    "email": "superadmin1@example.com",\n    "role": "SUPER_ADMIN",\n    "employeeId": "SA-1001",\n    "designation": "System Admin",\n    "phoneNumber": "+8801712345678",\n    "password": "123456"\n  }\n}',
        },
        file: { type: 'string', format: 'binary' },
      },
      required: ['data'],
    },
    examples: {
      STUDENT: {
        summary: 'STUDENT Registration',
        value: {
          data: '{\n  "firstName":"Student",\n  "lastName":"One",\n  "email":"student1@example.com",\n  "role":"STUDENT",\n  "departmentId":"3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
      },
      FACULTY: {
        summary: 'FACULTY Registration',
        value: {
          data: '{\n  "firstName":"Faculty",\n  "lastName":"One",\n  "email":"faculty1@example.com",\n  "role":"FACULTY",\n  "employeeId":"FAC-1001",\n  "designation":"Assistant Professor",\n  "departmentId":"3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
      },
      DEPARTMENT_HEAD: {
        summary: 'DEPARTMENT_HEAD Registration',
        value: {
          data: '{\n  "firstName":"Head",\n  "lastName":"OfDept",\n  "email":"head1@example.com",\n  "role":"DEPARTMENT_HEAD",\n  "employeeId":"DH-1001",\n  "designation":"Professor",\n  "departmentId":"3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
      },
      REGISTRAR: {
        summary: 'REGISTRAR Registration',
        value: {
          data: '{\n  "firstName":"Registrar",\n  "lastName":"One",\n  "email":"registrar1@example.com",\n  "role":"REGISTRAR",\n  "employeeId":"REG-1001",\n  "designation":"Registrar",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
      },
      SUPER_ADMIN: {
        summary: 'SUPER_ADMIN Registration',
        value: {
          data: '{\n  "firstName":"Super",\n  "lastName":"Admin",\n  "email":"superadmin1@example.com",\n  "role":"SUPER_ADMIN",\n  "employeeId":"SA-1001",\n  "designation":"System Admin",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
      },
    },
  })
  @Post()
  @UseInterceptors(FileInterceptor('file', { storage: multer.memoryStorage() }))
  async create(
    @Body() body: { data: string },
    @UploadedFile() image?: Express.Multer.File,
  ) {
    const parsed = JSON.parse(body.data) as unknown;
    let userRegistrationData: Partial<CreateUserDto> & { image?: string } = {};

    if (parsed && typeof parsed === 'object') {
      userRegistrationData = parsed as Partial<CreateUserDto> & {
        image?: string;
      };
    }

    if (image) {
      // console.log(image);
      // const imageLink = await uploadFileToS3(
      //   image,
      //   this.configService, // <-- important
      // );
      const imageLink = await uploadFileToCloudinary(
        image,
        this.configService,
        {
          folder: 'user-profile-images',
        },
      );
      // console.log('🚀 ~ UserController ~ create ~ imageLink:', imageLink);
      userRegistrationData.image = imageLink as string;
    }

    return this.userService.create(userRegistrationData as CreateUserDto);
  }

  @ApiOperation({ summary: 'Register STUDENT (multipart form-data)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          description:
            'studentId is auto-generated from departmentId. Do not send studentId.',
          example:
            '{\n  "firstName":"Student",\n  "lastName":"One",\n  "email":"student1@example.com",\n  "departmentId":"3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
        file: { type: 'string', format: 'binary' },
      },
      required: ['data'],
    },
  })
  @Post('/register/student')
  @UseInterceptors(FileInterceptor('file', { storage: multer.memoryStorage() }))
  registerStudent(
    @Body() body: { data: string },
    @UploadedFile() image?: Express.Multer.File,
  ) {
    return this.registerWithFixedRole(UserRole.STUDENT, body, image);
  }

  @ApiOperation({ summary: 'Register FACULTY (multipart form-data)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          example:
            '{\n  "firstName":"Faculty",\n  "lastName":"One",\n  "email":"faculty1@example.com",\n  "employeeId":"FAC-1001",\n  "designation":"Assistant Professor",\n  "departmentId":"3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
        file: { type: 'string', format: 'binary' },
      },
      required: ['data'],
    },
  })
  @Post('/register/faculty')
  @UseInterceptors(FileInterceptor('file', { storage: multer.memoryStorage() }))
  registerFaculty(
    @Body() body: { data: string },
    @UploadedFile() image?: Express.Multer.File,
  ) {
    return this.registerWithFixedRole(UserRole.FACULTY, body, image);
  }

  @ApiOperation({ summary: 'Register DEPARTMENT_HEAD (multipart form-data)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          example:
            '{\n  "firstName":"Head",\n  "lastName":"OfDept",\n  "email":"head1@example.com",\n  "employeeId":"DH-1001",\n  "designation":"Professor",\n  "departmentId":"3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
        file: { type: 'string', format: 'binary' },
      },
      required: ['data'],
    },
  })
  @Post('/register/department-head')
  @UseInterceptors(FileInterceptor('file', { storage: multer.memoryStorage() }))
  registerDepartmentHead(
    @Body() body: { data: string },
    @UploadedFile() image?: Express.Multer.File,
  ) {
    return this.registerWithFixedRole(UserRole.DEPARTMENT_HEAD, body, image);
  }

  @ApiOperation({ summary: 'Register REGISTRAR (multipart form-data)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          example:
            '{\n  "firstName":"Registrar",\n  "lastName":"One",\n  "email":"registrar1@example.com",\n  "employeeId":"REG-1001",\n  "designation":"Registrar",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
        file: { type: 'string', format: 'binary' },
      },
      required: ['data'],
    },
  })
  @Post('/register/registrar')
  @UseInterceptors(FileInterceptor('file', { storage: multer.memoryStorage() }))
  registerRegistrar(
    @Body() body: { data: string },
    @UploadedFile() image?: Express.Multer.File,
  ) {
    return this.registerWithFixedRole(UserRole.REGISTRAR, body, image);
  }

  @ApiOperation({ summary: 'Register SUPER_ADMIN (multipart form-data)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          example:
            '{\n  "firstName":"Super",\n  "lastName":"Admin",\n  "email":"superadmin1@example.com",\n  "employeeId":"SA-1001",\n  "designation":"System Admin",\n  "phoneNumber":"+8801712345678",\n  "password":"123456"\n}',
        },
        file: { type: 'string', format: 'binary' },
      },
      required: ['data'],
    },
  })
  @Post('/register/super-admin')
  @UseInterceptors(FileInterceptor('file', { storage: multer.memoryStorage() }))
  registerSuperAdmin(
    @Body() body: { data: string },
    @UploadedFile() image?: Express.Multer.File,
  ) {
    return this.registerWithFixedRole(UserRole.SUPER_ADMIN, body, image);
  }

  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Create user without OTP' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        firstName: { type: 'string' },
        lastName: { type: 'string' },
        email: { type: 'string' },
        role: {
          type: 'string',
          enum: [
            'SUPER_ADMIN',
            'REGISTRAR',
            'DEPARTMENT_HEAD',
            'FACULTY',
            'STUDENT',
          ],
        },
        employeeId: { type: 'string' },
        designation: { type: 'string' },
        departmentId: { type: 'string' },
        phoneNumber: { type: 'string' },
        password: { type: 'string' },
      },
      required: ['firstName', 'lastName', 'email', 'role', 'password'],
    },
    examples: {
      STUDENT: {
        summary: 'Create STUDENT',
        value: {
          firstName: 'Student',
          lastName: 'One',
          email: 'student1@example.com',
          role: 'STUDENT',
          departmentId: '3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a',
          phoneNumber: '+8801712345678',
          password: '123456',
        },
      },
      FACULTY: {
        summary: 'Create FACULTY',
        value: {
          firstName: 'Faculty',
          lastName: 'One',
          email: 'faculty1@example.com',
          role: 'FACULTY',
          employeeId: 'FAC-1001',
          designation: 'Assistant Professor',
          departmentId: '3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a',
          phoneNumber: '+8801712345678',
          password: '123456',
        },
      },
      DEPARTMENT_HEAD: {
        summary: 'Create DEPARTMENT_HEAD',
        value: {
          firstName: 'Head',
          lastName: 'OfDept',
          email: 'head1@example.com',
          role: 'DEPARTMENT_HEAD',
          employeeId: 'DH-1001',
          designation: 'Professor',
          departmentId: '3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a',
          phoneNumber: '+8801712345678',
          password: '123456',
        },
      },
      REGISTRAR: {
        summary: 'Create REGISTRAR',
        value: {
          firstName: 'Registrar',
          lastName: 'One',
          email: 'registrar1@example.com',
          role: 'REGISTRAR',
          employeeId: 'REG-1001',
          designation: 'Registrar',
          phoneNumber: '+8801712345678',
          password: '123456',
        },
      },
      SUPER_ADMIN: {
        summary: 'Create SUPER_ADMIN',
        value: {
          firstName: 'Super',
          lastName: 'Admin',
          email: 'superadmin1@example.com',
          role: 'SUPER_ADMIN',
          employeeId: 'SA-1001',
          designation: 'System Admin',
          phoneNumber: '+8801712345678',
          password: '123456',
        },
      },
    },
  })
  @Roles(ROLE.SUPER_ADMIN, ROLE.REGISTRAR)
  @Post('/create-user-without-otp')
  createUserWithoutOtp(@Body() createUserByAdmin: any) {
    return this.userService.createUserWithoutOtp(createUserByAdmin);
  }

  @ApiOperation({ summary: 'Resend registration OTP' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
      },
      required: ['email'],
    },
  })
  @Post('/resend-register-otp')
  resendRegistrationVerifyOtp(@Body('email') email: string) {
    return this.userService.resendRegistrationVerifyOtp(email);
  }

  @ApiOperation({ summary: 'Verify registration OTP' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
        otp: { type: 'string', example: '730689' },
      },
      required: ['email', 'otp'],
    },
  })
  @Post('/verify-register-otp')
  verifyRegisterOtp(@Body('email') email: string, @Body('otp') otp: string) {
    return this.userService.verifyRegisterOtp(email, otp);
  }

  @ApiOperation({ summary: 'Login with email and password' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
        password: { type: 'string', example: '123456' },
      },
      required: ['email', 'password'],
    },
  })
  @Post('/login')
  login(@Body('email') email: string, @Body('password') password: string) {
    return this.userService.login(email, password);
  }

  @ApiOperation({ summary: 'Resend login OTP' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
      },
      required: ['email'],
    },
  })
  @Post('/resend-login-otp')
  resendLoginOtp(@Body('email') email: string) {
    return this.userService.resendLoginOtp(email);
  }

  @ApiOperation({ summary: 'Verify login OTP' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
        otp: { type: 'string', example: '186355' },
      },
      required: ['email', 'otp'],
    },
  })
  @Post('/verify-login-otp')
  verifyLoginOtp(@Body('email') email: string, @Body('otp') otp: string) {
    return this.userService.verifyLoginOtp(email, otp);
  }

  @ApiOperation({ summary: 'Change password' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
        oldPassword: { type: 'string', example: '123456' },
        newPassword: { type: 'string', example: '12345678' },
      },
      required: ['email', 'oldPassword', 'newPassword'],
    },
  })
  @Post('/change-password')
  changePassword(
    @Body('email') email: string,
    @Body('oldPassword') oldPassword: string,
    @Body('newPassword') newPassword: string,
  ) {
    return this.userService.changePassword(email, oldPassword, newPassword);
  }

  @ApiOperation({ summary: 'Request forgotten-password OTP' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
      },
      required: ['email'],
    },
  })
  @Post('/forgotten-password')
  forgottenPassword(@Body('email') email: string) {
    return this.userService.forgottenPassword(email);
  }

  @ApiOperation({ summary: 'Verify forgotten-password OTP and reset password' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        email: { type: 'string', example: 'student@example.com' },
        otp: { type: 'string', example: '376277' },
        newPassword: { type: 'string', example: '25802580' },
      },
      required: ['email', 'otp', 'newPassword'],
    },
  })
  @Post('/verify-forgotten-password-otp')
  verifyForgottenPasswordOtp(
    @Body('email') email: string,
    @Body('otp') otp: string,
    @Body('newPassword') newPassword: string,
  ) {
    return this.userService.verifyForgottenPasswordOtp(email, otp, newPassword);
  }
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Update my profile (multipart form-data)' })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        data: {
          type: 'string',
          example:
            '{\n  "firstName":"Humayun",\n  "lastName":"Kabir",\n  "departmentId":"3f3a1ad2-8dc8-4d90-8a4b-3a9fe96e9f1a",\n  "designation":"Senior Lecturer"\n}',
        },
        file: { type: 'string', format: 'binary' },
      },
    },
  })
  @Roles(
    ROLE.SUPER_ADMIN,
    ROLE.REGISTRAR,
    ROLE.DEPARTMENT_HEAD,
    ROLE.FACULTY,
    ROLE.STUDENT,
  )
  @Patch('update-profile')
  @UseInterceptors(FileInterceptor('file', { storage: multer.memoryStorage() }))
  async updateProfile(
    @Req() req: Request & { user: any },
    @Body() body?: any,
    @UploadedFile() image?: Express.Multer.File,
  ) {
    let userUpdateData: any = {};

    // 🟢 BODY OPTIONAL
    if (body?.data) {
      try {
        const parsed = JSON.parse(body.data);
        userUpdateData = { ...parsed };
      } catch (err) {
        throw new BadRequestException('Invalid JSON format in data field');
      }
    }

    // 🟢 IMAGE OPTIONAL
    if (image) {
       const imageLink = await uploadFileToCloudinary(image, this.configService, {
        folder: 'user-profile-images',
      });
      userUpdateData.image = imageLink;
    }

    // ❌ nothing provided
    if (Object.keys(userUpdateData).length === 0) {
      throw new BadRequestException('No update data provided');
    }

    return this.userService.updateProfile(req.user.id, userUpdateData);
  }

  @Patch('block-user/:id')
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Block a user' })
  @ApiParam({ name: 'id', type: String, example: '076d47db-86cb-4116-8626-1cda8fa4920c' })
  @Roles(ROLE.SUPER_ADMIN, ROLE.REGISTRAR)
  blockUser(@Param('id') id: string) {
    return this.userService.blockUser(id);
  }

  @Patch('unblock-user/:id')
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Unblock a user' })
  @ApiParam({ name: 'id', type: String, example: '076d47db-86cb-4116-8626-1cda8fa4920c' })
  @Roles(ROLE.SUPER_ADMIN, ROLE.REGISTRAR)
  unblockUser(@Param('id') id: string) {
    return this.userService.unblockUser(id);
  }

  @Patch('change-role/:id')
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Change a user role' })
  @ApiParam({ name: 'id', type: String, example: '076d47db-86cb-4116-8626-1cda8fa4920c' })
  @ApiBody({
    schema: {
      type: 'object',
      properties: {
        role: {
          type: 'string',
          enum: [
            'SUPER_ADMIN',
            'REGISTRAR',
            'DEPARTMENT_HEAD',
            'FACULTY',
            'STUDENT',
          ],
          example: 'STUDENT',
        },
      },
      required: ['role'],
    },
  })
  @Roles(ROLE.SUPER_ADMIN, ROLE.REGISTRAR)
  changeRole(@Param('id') id: string, @Body('role') role: UserRole) {
    return this.userService.changeRole(id, role);
  }

  @Delete('delete-user/:id')
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Soft delete a user' })
  @ApiParam({ name: 'id', type: String, example: '076d47db-86cb-4116-8626-1cda8fa4920c' })
  @Roles(ROLE.SUPER_ADMIN, ROLE.REGISTRAR)
  deleteUser(@Param('id') id: string) {
    return this.userService.deleteUser(id);
  }

  @Delete('delete-myself-account')
  @UseGuards(AuthGuard)
  @ApiSecurity('token-auth')
  @ApiOperation({ summary: 'Soft delete my own account' })
  @Roles(
    ROLE.SUPER_ADMIN,
    ROLE.REGISTRAR,
    ROLE.DEPARTMENT_HEAD,
    ROLE.FACULTY,
    ROLE.STUDENT,
  )
  deleteMyselfAccount(@Req() req: Request & { user: any }) {
    return this.userService.deleteMyselfAccount(req.user.id);
  }
}
